services:
  postgres:
    image: postgres:17.6-alpine
    hostname: postgres
    networks:
      - default
    expose:
      - 5432
    env_file:
      - env-example-relational
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    networks:
      - default
    hostname: maildev
    env_file:
      - env-example-relational
    expose:
      - 1080
      - 1025

  #  Uncomment to use redis
  redis:
    image: redis:7-alpine
    hostname: redis
    networks:
      - default
    env_file:
      - env-example-relational
    expose:
      - 6379

  api:
    build:
      context: .
      dockerfile: relational.test.Dockerfile
    networks:
      - default
    expose:
      - 3000
      - 4000
    env_file:
      - env-example-relational
